# -*- coding: utf-8 -*-
"""Cluster Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9ysLXBGcLQy33i2haowm_2Nsxepyyj6
"""

!pip install -q google-cloud-aiplatform supabase

import numpy as np
import pandas as pd
import json
import time
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import auth, userdata
from supabase import create_client, Client
import vertexai
from vertexai.generative_models import GenerativeModel

SUPABASE_URL = userdata.get('SUPABASE_URL')
SUPABASE_KEY = userdata.get('SUPABASE_KEY')

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

auth.authenticate_user()

vertexai.init(
    project="gen-lang-client-0336229125",
    location="us-central1"
)

gemini = GenerativeModel("gemini-2.5-flash-lite")

print("Clients ready.")

print("Pulling article_analysis...")
analysis_response = supabase.table("article_analysis").select(
    "doc_id, cluster_id, bert_embeddings, stage, risk_score"
).execute()
df_analysis = pd.DataFrame(analysis_response.data)

print("Pulling articles_v1...")
articles_response = supabase.table("articles_v1").select(
    "doc_id, title, raw_text"
).execute()
df_articles = pd.DataFrame(articles_response.data)

print(f"article_analysis rows: {len(df_analysis)}")
print(f"articles_v1 rows: {len(df_articles)}")

df = pd.merge(df_analysis, df_articles, on="doc_id", how="left")

def parse_embedding(val):
    if isinstance(val, list):
        return np.array(val)
    if isinstance(val, str):
        try:
            return np.array(json.loads(val))
        except:
            return None
    return None

def safe_text(val):
    if isinstance(val, str):
        return val[:500]
    return ''

df['embedding_parsed'] = df['bert_embeddings'].apply(parse_embedding)
df = df[df['embedding_parsed'].notna()].copy()

print(f"Total articles after merge + parse: {len(df)}")
print(f"Clusters found: {df['cluster_id'].nunique()}")

cluster_ids = sorted(df['cluster_id'].dropna().unique())
cluster_ids = [int(c) for c in cluster_ids if int(c) != -1]

nearest_article_updates = []
cluster_centroids = {}

for cluster_id in cluster_ids:
    cluster_df = df[df['cluster_id'] == cluster_id].copy()

    if len(cluster_df) == 0:
        continue

    embeddings_matrix = np.array(cluster_df['embedding_parsed'].tolist())
    centroid = embeddings_matrix.mean(axis=0).reshape(1, -1)
    cluster_centroids[cluster_id] = centroid

    similarities = cosine_similarity(embeddings_matrix, centroid).flatten()
    cluster_df['similarity_to_centroid'] = similarities

    nearest_idx = cluster_df['similarity_to_centroid'].idxmax()
    nearest_doc_id = cluster_df.loc[nearest_idx, 'doc_id']

    for _, row in cluster_df.iterrows():
        nearest_article_updates.append({
            "doc_id": row['doc_id'],
            "nearest_article": row['doc_id'] == nearest_doc_id
        })

    print(f"Cluster {cluster_id}: nearest article → {nearest_doc_id}")

print(f"\nTotal nearest_article flags prepared: {len(nearest_article_updates)}")

import re

cluster_themes_rows = []

for cluster_id in cluster_ids:
    cluster_df = df[df['cluster_id'] == cluster_id].copy()

    if len(cluster_df) == 0:
        continue

    print(f"\nLabeling cluster {cluster_id} ({len(cluster_df)} articles)...")

    centroid = cluster_centroids[cluster_id]
    embeddings_matrix = np.array(cluster_df['embedding_parsed'].tolist())
    similarities = cosine_similarity(embeddings_matrix, centroid).flatten()
    cluster_df['similarity_to_centroid'] = similarities

    top_articles = cluster_df.nlargest(10, 'similarity_to_centroid')

    context_chunks = []
    for _, row in top_articles.iterrows():
        title = row.get('title', '')
        text = safe_text(row.get('raw_text'))
        context_chunks.append(f"TITLE: {title}\nSNIPPET: {text}")

    context_text = "\n\n---\n\n".join(context_chunks)

    prompt = f"""
You are a fraud intelligence analyst specializing in financial crime.

Below are article titles and snippets from a cluster of related articles.

Analyze them and return ONLY a JSON object with exactly these fields:
- "theme_label": a short 2-5 word FRAUD-SPECIFIC theme label focused on the criminal scheme or threat vector (e.g. "BEC Email Phishing", "Synthetic Identity Fraud", "Crypto Money Laundering"). Do NOT use generic business terms like "Fintech Innovation" or "AI Investment".
- "theme_description": 1-2 sentences describing the specific fraud pattern or criminal threat this cluster represents.

If the articles do not clearly represent a fraud theme, still identify the closest fraud risk or threat angle.

Do not include any preamble, markdown, or explanation. Return only valid JSON.

Articles:
{context_text}
"""

    try:
        response = gemini.generate_content(prompt)
        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        raw = re.sub(r',\s*}', '}', raw)
        raw = re.sub(r',\s*]', ']', raw)

        parsed = json.loads(raw)
        theme_label = parsed.get("theme_label", "Unknown")
        theme_description = parsed.get("theme_description", "")

    except Exception as e:
        print(f"  ❌ Gemini error for cluster {cluster_id}: {e}")
        theme_label = "Unknown"
        theme_description = ""

    evidence_doc_ids = cluster_df['doc_id'].tolist()
    stage = cluster_df['stage'].mode()[0] if 'stage' in cluster_df.columns else None
    risk_score = float(cluster_df['risk_score'].max()) if 'risk_score' in cluster_df.columns else None

    cluster_themes_rows.append({
        "cluster_id": cluster_id,
        "theme_label": theme_label,
        "theme_description": theme_description,
        "theme_evidence": evidence_doc_ids,
        "article_count": len(cluster_df),
        "stage": stage,
        "risk_score": risk_score
    })

    print(f"  Theme: {theme_label}")
    time.sleep(2)

print(f"\nTotal clusters labeled: {len(cluster_themes_rows)}")

import re

unknown_clusters = [row for row in cluster_themes_rows if row['theme_label'] == 'Unknown']
print(f"Re-labeling {len(unknown_clusters)} Unknown clusters...")

for row in unknown_clusters:
    cluster_id = row['cluster_id']
    cluster_df = df[df['cluster_id'] == cluster_id].copy()

    centroid = cluster_centroids[cluster_id]
    embeddings_matrix = np.array(cluster_df['embedding_parsed'].tolist())
    similarities = cosine_similarity(embeddings_matrix, centroid).flatten()
    cluster_df['similarity_to_centroid'] = similarities

    top_articles = cluster_df.nlargest(10, 'similarity_to_centroid')

    context_chunks = []
    for _, r in top_articles.iterrows():
        title = r.get('title', '')
        text = safe_text(r.get('raw_text'))
        context_chunks.append(f"TITLE: {title}\nSNIPPET: {text}")

    context_text = "\n\n---\n\n".join(context_chunks)

    prompt = f"""
You are a fraud intelligence analyst specializing in financial crime.

Below are article titles and snippets from a cluster of related articles.

Analyze them and return ONLY a JSON object with exactly these fields:
- "theme_label": a short 2-5 word FRAUD-SPECIFIC theme label focused on the criminal scheme or threat vector (e.g. "BEC Email Phishing", "Synthetic Identity Fraud", "Crypto Money Laundering"). Do NOT use generic business terms like "Fintech Innovation" or "AI Investment".
- "theme_description": 1-2 sentences describing the specific fraud pattern or criminal threat this cluster represents.

If the articles do not clearly represent a fraud theme, still identify the closest fraud risk or threat angle.

Do not include any preamble, markdown, or explanation. Return only valid JSON.

Articles:
{context_text}
"""

    try:
        response = gemini.generate_content(prompt)
        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        raw = re.sub(r',\s*}', '}', raw)
        raw = re.sub(r',\s*]', ']', raw)

        parsed = json.loads(raw)
        row['theme_label'] = parsed.get("theme_label", "Unknown")
        row['theme_description'] = parsed.get("theme_description", "")
        print(f"  Cluster {cluster_id}: {row['theme_label']}")

    except Exception as e:
        print(f"  ❌ Cluster {cluster_id} failed again: {e}")

    time.sleep(2)

print("\nRe-labeling complete.")

CHUNK_SIZE = 50

print(f"Upserting {len(cluster_themes_rows)} rows to cluster_themes...")

for i in range(0, len(cluster_themes_rows), CHUNK_SIZE):
    chunk = cluster_themes_rows[i:i + CHUNK_SIZE]
    try:
        supabase.table("cluster_themes").upsert(
            chunk,
            on_conflict="cluster_id"
        ).execute()
        print(f"✅ cluster_themes: {min(i + CHUNK_SIZE, len(cluster_themes_rows))}/{len(cluster_themes_rows)}")
    except Exception as e:
        print(f"❌ Error at chunk {i}: {e}")

print("cluster_themes upsert complete.")

print(f"Upserting {len(nearest_article_updates)} nearest_article flags...")

for i in range(0, len(nearest_article_updates), CHUNK_SIZE):
    chunk = nearest_article_updates[i:i + CHUNK_SIZE]
    try:
        supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"✅ nearest_article: {min(i + CHUNK_SIZE, len(nearest_article_updates))}/{len(nearest_article_updates)}")
    except Exception as e:
        print(f"❌ Error at chunk {i}: {e}")

print("nearest_article flags upsert complete.")