# -*- coding: utf-8 -*-
"""DSBA6390 Fraud Detection BERT + Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqympIQ1ns43GF84FYU90quCctESCffC

# Bringing in Data from Supabase
"""

pip install supabase

from supabase import create_client, Client
from google.colab import userdata

# Retrieve credentials from Colab secrets
SUPABASE_URL = userdata.get('SUPABASE_URL')
SUPABASE_KEY = userdata.get('SUPABASE_KEY')

# Create a Supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Supabase client created successfully.")

import pandas as pd

response = supabase.table('articles_v1').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df.head())

df.shape

print(f"Shape before removing duplicates: {df.shape}")
df.drop_duplicates(subset=['doc_id'], inplace=True)
print(f"Shape after removing duplicates: {df.shape}")
display(df.head())

import google.generativeai as genai
from google.colab import userdata

# Retrieve the Gemini API key from Colab secrets
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

# Configure the google.generativeai library
genai.configure(api_key=GEMINI_API_KEY)

print("Gemini API key retrieved and Generative AI library configured.")

import re

def clean_text(text):
    if not isinstance(text, str):
        return ""
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers, keep only letters and spaces
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("Text cleaning function 'clean_text' defined.")

df['cleaned_text'] = df['raw_text'].apply(clean_text)
display(df.head())

df = df[df['cleaned_text'] != '']
display(df.head())
print(f"New DataFrame shape: {df.shape}")

import pandas as pd

response = supabase.table('article_embeddings').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df_embeddings = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df_embeddings.head())

print(df_embeddings.columns.tolist())

df_embeddings.shape

import pandas as pd
import google.generativeai as genai
import os


for var in ['HTTP_PROXY', 'HTTPS_PROXY', 'http_proxy', 'https_proxy']:
    os.environ.pop(var, None)

# Configure with an explicit endpoint to bypass local network redirects
genai.configure(
    api_key=GEMINI_API_KEY,
    client_options={'api_endpoint': 'generativelanguage.googleapis.com'}
)

df['doc_id'] = df['doc_id'].astype(str)
df_embeddings['doc_id'] = df_embeddings['doc_id'].astype(str)

if 'embedding' in df.columns:
    df.drop(columns=['embedding'], inplace=True)

# Merge
df = df.merge(df_embeddings[['doc_id', 'embedding']], on='doc_id', how='left')

missing_mask = df['embedding'].isna()
indices_to_embed = df[missing_mask].index

if not indices_to_embed.empty:
    print(f"Generating embeddings for {len(indices_to_embed)} new documents...")

    # Process in batches of 50
    BATCH_SIZE = 50

    for i in range(0, len(indices_to_embed), BATCH_SIZE):
        batch_indices = indices_to_embed[i : i + BATCH_SIZE]
        batch_texts = df.loc[batch_indices, 'cleaned_text'].tolist()

        try:
            response = genai.embed_content(
                model="models/gemini-embedding-001",
                content=batch_texts,
                task_type="retrieval_document"
            )


            embeddings_list = response['embedding']


            df.loc[batch_indices, 'embedding'] = pd.Series(embeddings_list, index=batch_indices)

            print(f"Success: Processed up to row {i + len(batch_texts)}")

        except Exception as e:
            print(f"Error at index {i}: {e}")

else:
    print("All documents already have embeddings.")

print(f"Total rows: {len(df)}")
print(f"Rows with embeddings: {df['embedding'].notna().sum()}")

import numpy as np

# 1. Clean the data (Crucial: Supabase needs standard Python lists, not Numpy arrays)
df_new_ready = df[df['embedding'].notna()][['doc_id', 'embedding']].copy()
df_new_ready['embedding'] = df_new_ready['embedding'].apply(
    lambda x: x.tolist() if isinstance(x, np.ndarray) else x
)

# 2. Convert to list of dicts
data_to_upsert = df_new_ready.to_dict(orient='records')

# 3. Upsert in smaller chunks to avoid Database Timeout
CHUNK_SIZE = 50
print(f"Upserting {len(data_to_upsert)} rows in chunks of {CHUNK_SIZE}...")

for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_embeddings").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"Successfully upserted chunk {i//CHUNK_SIZE + 1} ({min(i + CHUNK_SIZE, len(data_to_upsert))} rows total)")
    except Exception as e:
        print(f"Failed at chunk starting at index {i}: {e}")

import numpy as np
import google.generativeai as genai

# Define the get_gemini_embeddings function
def get_gemini_embeddings(text):
    try:
        # Ensure text is a list, as embed_content can take a list of strings
        if isinstance(text, str):
            text = [text]

        response = genai.embed_content(
            model="models/gemini-embedding-001",
            content=text,
            task_type="retrieval_document" # Or "retrieval_query" depending on use case
        )
        # For a single text input, return the first embedding
        return response['embedding'][0]
    except Exception as e:
        print(f"Error generating embedding for text: {text}. Error: {e}")
        return None

fraud_concepts = [
    "financial fraud",
    "identity theft",
    "phishing scam",
    "money laundering",
    "cybercrime",
    "account takeover"
]

# Apply get_gemini_embeddings to each concept and convert to NumPy array
fraud_embeddings_list = [get_gemini_embeddings(concept) for concept in fraud_concepts]

# Filter out any None values if embedding generation failed for some concepts
fraud_embeddings_list = [emb for emb in fraud_embeddings_list if emb is not None]

# Only proceed if there are valid embeddings
if fraud_embeddings_list:
    fraud_embeddings_array = np.array(fraud_embeddings_list)

    # Calculate the mean across the rows (axis=0) to get a single fraud_embedding vector
    fraud_embedding = fraud_embeddings_array.mean(axis=0)

    print("Fraud embedding calculated successfully.")
else:
    print("No fraud embeddings could be generated.")

print(f"Shape of fraud_embedding: {fraud_embedding.shape}")

import numpy as np
import ast # Required for safely evaluating string literals

# Function to safely parse an embedding value into a list of floats
def parse_embedding_to_list(embed_value):
    if isinstance(embed_value, str):
        try:
            # Use ast.literal_eval to safely convert string to Python literal (list, tuple, etc.)
            parsed = ast.literal_eval(embed_value)
            if isinstance(parsed, (list, tuple)):
                return [float(x) for x in parsed] # Ensure elements are floats
        except (ValueError, SyntaxError):
            return None # Not a valid string representation of a list
    elif isinstance(embed_value, np.ndarray):
        return embed_value.tolist()
    elif isinstance(embed_value, list):
        # Ensure it's a list of floats
        return [float(x) for x in embed_value]
    return None # For any other unexpected types or None values

# Apply the conversion to the 'embedding' column of the DataFrame
df['embedding'] = df['embedding'].apply(parse_embedding_to_list)

# Filter out any rows where the embedding could not be properly parsed or resulted in None
# This ensures that all elements in the list passed to np.array are valid lists of floats
valid_embeddings_list = [embed for embed in df['embedding'] if embed is not None and isinstance(embed, list)]

# Check for consistency in embedding dimensions before creating the NumPy array
if valid_embeddings_list:
    first_embedding_length = len(valid_embeddings_list[0])
    # Ensure all embeddings have the same dimension
    if not all(len(embed) == first_embedding_length for embed in valid_embeddings_list):
        print("Warning: Some embeddings have inconsistent lengths after cleaning. Proceeding with available consistent ones.")
        # Further filter to only include embeddings of the most common length, or raise an error.
        # For now, we will create the array from the cleaned list, which should be consistent if generation was.

    text_embedding_array = np.array(valid_embeddings_list)
    print(f"Shape of text_embedding_array: {text_embedding_array.shape}")
else:
    print("Warning: No valid embeddings found after cleaning. 'text_embedding_array' will be an empty array.")
    text_embedding_array = np.array([]) # Create an empty array if no valid embeddings

fraud_embedding_2d = fraud_embedding.reshape(1, -1)
print(f"Shape of fraud_embedding_2d: {fraud_embedding_2d.shape}")

from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(text_embedding_array, fraud_embedding_2d)
df['fraud_similarity'] = similarity_scores.flatten()
display(df.head())

filtered_df = df[df['fraud_similarity'] > 0.4]

display(filtered_df.head())
print(f"Shape of filtered_df: {filtered_df.shape}")

"""# BERT"""

import pandas as pd

response = supabase.table('article_analysis').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df_bert_embeddings = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df_bert_embeddings.head())

df_bert_embeddings.shape

!pip install tf-keras
!pip install transformers==4.42.0

import tf_keras
print(tf_keras.__version__)

import numpy as np
import pandas as pd
import tensorflow as tf
import transformers

max_length = 128  # Maximum length of input sentence to the model.
batch_size = 32
epochs = 2

class BertInputBatchGenerator(tf_keras.utils.Sequence):

    def __init__(
        self,
        sentence_pairs,
        labels,
        batch_size=batch_size,
        shuffle=True,
        include_targets=True,
    ):
        self.sentence_pairs = sentence_pairs
        self.labels = labels
        self.shuffle = shuffle
        self.batch_size = batch_size
        self.include_targets = include_targets
        # Load our BERT Tokenizer to encode the text.
        # We will use bert-base-uncased pretrained model.
        self.tokenizer = transformers.BertTokenizer.from_pretrained(
            "bert-base-uncased", do_lower_case=True
        )
        self.indexes = np.arange(len(self.sentence_pairs))
        self.on_epoch_end()

    def __len__(self):
        # Return the number of batches per epoch.
        return len(self.sentence_pairs) // self.batch_size

    def __getitem__(self, idx):
        # Retrieves the batch of index.
        indexes = self.indexes[idx * self.batch_size : (idx + 1) * self.batch_size]
        sentence_pairs = self.sentence_pairs[indexes]

        # With BERT tokenizer's batch_encode_plus, batch of both the sentences are
        # encoded together and separated by [SEP] token.
        encoded = self.tokenizer.batch_encode_plus(
            sentence_pairs.tolist(),
            add_special_tokens=True,
            max_length=max_length,
            return_attention_mask=True,
            return_token_type_ids=True,
            padding='max_length', # Changed from pad_to_max_length=True
            truncation=True, # Added truncation=True
            return_tensors="tf",
        )

        # Convert batch of encoded features to numpy array.
        input_ids = np.array(encoded["input_ids"], dtype="int32")
        attention_masks = np.array(encoded["attention_mask"], dtype="int32")
        token_type_ids = np.array(encoded["token_type_ids"], dtype="int32")

        # Set to true if the data generator is used for training/validation.
        if self.include_targets:
            labels = np.array(self.labels[indexes], dtype="int32")
            return [input_ids, attention_masks, token_type_ids], labels
        else:
            return [input_ids, attention_masks, token_type_ids]

    def on_epoch_end(self):
        # Shuffle indexes after each epoch if shuffle is set to True.
        if self.shuffle:
            np.random.RandomState(42).shuffle(self.indexes)

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    # Encoded token ids from BERT tokenizer.
    input_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="input_ids"
    )
    # Attention masks indicate which tokens are real and which are fake (padding).
    attention_masks = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="attention_masks"
    )
    # Token type ids indicate which tokens belong to Sentence 1 and which to Sentence 2.
    token_type_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="token_type_ids"
    )
    # Loading pretrained BERT model.
    bert_model = transformers.TFBertModel.from_pretrained("bert-base-uncased")
    # Freeze the BERT model to reuse the pretrained features without modifying them.
    bert_model.trainable = False

    # Explicit conversion of KerasTensors to tf.Tensors
    bert_output = bert_model.bert(
        input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids
    )
    sequence_output = bert_output.last_hidden_state
    pooled_output = bert_output.pooler_output

    # Add trainable layers on top of frozen layers to adapt the pretrained features on the new data.
    bi_lstm = tf_keras.layers.Bidirectional(
        tf_keras.layers.LSTM(64, return_sequences=True)
    )(sequence_output)
    # Applying hybrid pooling approach to bi_lstm sequence output.
    avg_pool = tf_keras.layers.GlobalAveragePooling1D()(bi_lstm)
    dropout = tf_keras.layers.Dropout(0.3)(avg_pool)
    output = tf_keras.layers.Dense(3, activation="softmax")(dropout)


    model = tf_keras.Model(
        inputs=[input_ids, attention_masks, token_type_ids], outputs=output
    )

    model.compile(
        optimizer=tf_keras.optimizers.Adam(),
        loss="categorical_crossentropy",
        metrics=["acc"],
    )


print(f"Strategy: {strategy}")
model.summary()

import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import pandas as pd # Ensure pandas is imported for value_counts()

# Identify IDs that already have embeddings
existing_ids = df_bert_embeddings['doc_id'].unique()

# Filter filtered_df for IDs that are NOT in the existing_ids list
to_process_df = filtered_df[~filtered_df['doc_id'].isin(existing_ids)].copy()

if to_process_df.empty:
    print("All articles already have embeddings. Nothing to do!")
else:
    print(f"New articles to process: {len(to_process_df)}")

    num_classes = 3
    # Use the length of the filtered subset
    new_dummy_labels = np.random.randint(0, num_classes, size=len(to_process_df))

    # This was the missing function
    ohe_labels = to_categorical(new_dummy_labels, num_classes=num_classes)

    # Split the NEW data into training and validation sets
    # Added 'ids_train' and 'ids_val' so you can map embeddings back to doc_ids later
    if len(to_process_df) <= 1: # Cannot split if 1 or 0 samples for train_test_split with test_size > 0
        X_train = to_process_df['cleaned_text'].values
        y_train = ohe_labels
        ids_train = to_process_df['doc_id'].values
        X_val = np.array([])
        y_val = np.array([])
        ids_val = np.array([])
        print("Not enough samples to perform train_test_split. Skipping validation set creation.")
    else:
        # Check if stratification is possible
        class_counts = pd.Series(new_dummy_labels).value_counts()
        min_samples_per_class = class_counts.min()

        if min_samples_per_class < 2: # Cannot stratify if any class has less than 2 samples
            print("Warning: Not enough samples per class for stratification. Performing non-stratified split.")
            X_train, X_val, y_train, y_val, ids_train, ids_val = train_test_split(
                to_process_df['cleaned_text'].values,
                ohe_labels,
                to_process_df['doc_id'].values,
                test_size=0.2,
                random_state=42 # No stratification
            )
        else:
            # Perform stratified split
            X_train, X_val, y_train, y_val, ids_train, ids_val = train_test_split(
                to_process_df['cleaned_text'].values,
                ohe_labels,
                to_process_df['doc_id'].values,
                test_size=0.2,
                random_state=42,
                stratify=new_dummy_labels
            )

    # Create generators for the new batch
    # Make sure 'batch_size' is defined (e.g., batch_size = 16 or 32)
    train_data_generator = BertInputBatchGenerator(
        X_train, y_train, batch_size=batch_size, shuffle=True
    )
    # Only create valid_data_generator if X_val is not empty
    if len(X_val) > 0:
        valid_data_generator = BertInputBatchGenerator(
            X_val, y_val, batch_size=batch_size, shuffle=False
        )
    else:
        valid_data_generator = None # Or an empty generator if the model expects one

    print(f"Incremental setup complete for {len(to_process_df)} articles.")

import numpy as np
import transformers

# Initialize the tokenizer globally
tokenizer = transformers.BertTokenizer.from_pretrained(
    "bert-base-uncased", do_lower_case=True
)

# We will directly use to_process_df which contains the new articles identified
if not to_process_df.empty:
    print(f"🛠️ Generating 768-dim BERT features for {len(to_process_df)} new articles...")

    # 2. Tokenize the cleaned text of the new articles
    encoded_new_articles = tokenizer.batch_encode_plus(
        to_process_df['cleaned_text'].fillna("").astype(str).tolist(),
        add_special_tokens=True,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors="tf"
    )

    # 3. Model Inference - Get embeddings from the BERT layer
    try:
        # Assuming your base BERT model variable is 'bert_model'
        outputs = bert_model.bert(
            input_ids=encoded_new_articles['input_ids'],
            attention_mask=encoded_new_articles['attention_mask'],
            token_type_ids=encoded_new_articles['token_type_ids']
        )
        raw_vectors = outputs.pooler_output.numpy()
    except Exception as e:
        print(f"Error using bert_model.bert: {e}")
        print("Falling back to model.layers[0] to extract BERT embeddings...")
        # Fallback: Try accessing the first layer of your current 'model'
        bert_layer_output = model.layers[0](
            [encoded_new_articles['input_ids'],
             encoded_new_articles['attention_mask'],
             encoded_new_articles['token_type_ids']]
        )
        raw_vectors = bert_layer_output.pooler_output.numpy()

    # 4. Sanitize and Verify
    sanitized_vectors = np.nan_to_num(raw_vectors, nan=0.0).tolist()

    print(f"✅ Generated {len(sanitized_vectors)} vectors.")
    print(f"📏 New Dimension Check: {len(sanitized_vectors[0])} (Target: 768)")

    # 5. Create a DataFrame for new embeddings
    new_embeddings_df = pd.DataFrame({
        'doc_id': to_process_df['doc_id'].values,
        'bert_embeddings': sanitized_vectors
    })

    # 6. Append new embeddings to df_bert_embeddings
    # Ensure we don't duplicate if for some reason an ID exists but was in to_process_df
    df_bert_embeddings = pd.concat([df_bert_embeddings,
                                    new_embeddings_df[~new_embeddings_df['doc_id'].isin(df_bert_embeddings['doc_id'])]],
                                   ignore_index=True)

    print(f"Updated df_bert_embeddings shape: {df_bert_embeddings.shape}")
else:
    print("No new articles to process for BERT embeddings.")

df_bert_embeddings.shape

import numpy as np
import json
import pandas as pd
import math

# 1. Force sync and SELECT ONLY NECESSARY COLUMNS
# This is the most important change: we drop everything except ID and Vector
df_final = df_bert_embeddings[['doc_id', 'bert_embeddings']].copy()

if 'bert_embeddings' in df_final.columns:
    df_final = df_final.rename(columns={'bert_embeddings': 'bert_embeddings'})

print(f"Starting surgical pipeline: {len(df_final)} rows found.")

# 2. BRUTE FORCE Sanitization (Re-running to be 100% safe)
def final_sanitizer(val):
    vec = None
    if isinstance(val, str):
        try: vec = json.loads(val)
        except: return None
    elif isinstance(val, (list, np.ndarray)):
        vec = list(val)

    if vec and len(vec) == 768:
        # Check every float. If it's NaN/Inf, it MUST become 0.0
        return [float(x) if math.isfinite(float(x)) else 0.0 for x in vec]
    return None

df_final['bert_embeddings'] = df_final['bert_embeddings'].apply(final_sanitizer)

# 3. Validation
df_final = df_final.dropna(subset=['bert_embeddings'])
final_count = len(df_final)
print(f"Validated {final_count} rows.")

# 4. Upsert Execution - strictly doc_id and bert_embeddings
# This creates a list of dicts with ONLY two keys
data_to_upsert = df_final[['doc_id', 'bert_embeddings']].to_dict(orient='records')
CHUNK_SIZE = 50

print(f"Upserting {len(data_to_upsert)} rows to Supabase...")
for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"✅ Progress: {min(i + CHUNK_SIZE, final_count)}/{final_count}")
    except Exception as e:
        print(f"❌ Error at chunk {i}: {e}")
        # If it still fails, the error isn't in the vector.
        # Check the ID itself.
        if i == 0:
             print(f"Sample Row Keys: {chunk[0].keys()}")

print("Database synchronization complete.")

"""#Clustering"""

import numpy as np

# Convert the list of 768-dim vectors into a single 2D NumPy array (909, 768)
embeddings_matrix = np.array(df_final['bert_embeddings'].tolist())

# Final sanity check: ensure no NaNs survived
if np.isnan(embeddings_matrix).any():
    print("⚠️ Found NaNs in matrix. Replacing with 0.0...")
    embeddings_matrix = np.nan_to_num(embeddings_matrix)

print(f"Matrix shape ready for UMAP: {embeddings_matrix.shape}")

import umap
import hdbscan
from sklearn.metrics import silhouette_score

# 1. Compress 768D BERT to 5D UMAP
reducer = umap.UMAP(
    n_neighbors=5,       # CRITICAL: Lowering this forces BERT to find tiny, local groups
    n_components=5,      # Keep 5D to allow for clear density separation
    metric='cosine',
    min_dist=0.0,        # Ensure points overlap as little as possible
    random_state=42
)
u_embeddings = reducer.fit_transform(embeddings_matrix)

# 2. Run HDBSCAN on the COMPRESSED data
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=5,  # Smallest possible valid "topic"
    min_samples=1,       # Don't ignore "borderline" points
    cluster_selection_method='leaf', # Pick the most specific sub-clusters
    metric='euclidean'
)
new_labels = clusterer.fit_predict(u_embeddings)

# 3. Re-calculate Silhouette (excluding noise -1 for a fair test)
mask = new_labels != -1
if mask.any():
    score = silhouette_score(u_embeddings[mask], new_labels[mask])
    print(f"New Silhouette Score: {score:.4f}")
    print(pd.Series(new_labels).value_counts())

# First, ensure filtered_df has the BERT embeddings from df_final

# Drop any existing bert_embeddings columns that might have accumulated
# from previous runs or merges.
cols_to_drop = [col for col in filtered_df.columns if 'bert_embeddings' in col]
if cols_to_drop:
    filtered_df.drop(columns=cols_to_drop, inplace=True)

# Now perform the merge to add bert_embeddings to filtered_df
# This will ensure filtered_df has the bert_embeddings for its existing 1000 articles
filtered_df = pd.merge(filtered_df, df_final[['doc_id', 'bert_embeddings']], on='doc_id', how='left')

# Add new_labels and clusterer.probabilities_ to df_final first, as they are aligned by index
df_final['cluster_id'] = new_labels
df_final['cluster_density'] = clusterer.probabilities_

# Now merge the cluster information from df_final into filtered_df
# This will add 'cluster_id' and 'cluster_density' columns to filtered_df,
# matching on 'doc_id' and only for the 1000 articles present in filtered_df.
# Using a left merge here is appropriate to keep all articles from filtered_df.
filtered_df = pd.merge(
    filtered_df,
    df_final[['doc_id', 'cluster_id', 'cluster_density']],
    on='doc_id',
    how='left'
)

# Handle potential NaNs for cluster_id if any doc_id in filtered_df was not in df_final
# (Unlikely given the flow, but good practice). HDBSCAN's -1 is integer, so fillna(-1) then astype(int).
filtered_df['cluster_id'] = filtered_df['cluster_id'].fillna(-1).astype(int)

print(filtered_df)

# Create a lean dataframe for the initial upsert
df_clusters = filtered_df[['doc_id', 'cluster_id']].copy()

# Ensure cluster_id is a standard Python int (Supabase/Postgres requirement)
df_clusters['cluster_id'] = df_clusters['cluster_id'].astype(int)

# Convert to list of dictionaries
data_to_upsert = df_clusters.to_dict(orient='records')

CHUNK_SIZE = 100
print(f"Updating cluster_id for {len(data_to_upsert)} rows...")

for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"✅ Updated chunk {i//CHUNK_SIZE + 1}")
    except Exception as e:
        print(f"❌ Error at index {i}: {e}")

# if cluster spikes, potentially an emerging threat
filtered_df['publish_timestamp'] = pd.to_datetime(filtered_df['publish_timestamp'])
filtered_df.info()

filtered_df['week'] = filtered_df['publish_timestamp'].dt.isocalendar().week
display(filtered_df.head())

cluster_counts_by_week = filtered_df.groupby(['week', 'cluster_id']).size().reset_index(name='count')
display(cluster_counts_by_week)

# Create time component that tracks established threat/emerging threat
# Drop rows where 'publish_timestamp' is NaT before creating the 'week' column
# This ensures that the 'week' column is consistently populated with valid Period objects
filtered_df = filtered_df.dropna(subset=['publish_timestamp']).copy()
filtered_df['week'] = filtered_df['publish_timestamp'].dt.to_period('W')

cluster_stats_list = []

for week in sorted(filtered_df['week'].unique()):
    weekly_df = filtered_df[filtered_df['week'] == week]

    for cluster_id in sorted(weekly_df['cluster_id'].unique()):
        # Exclude noise points (cluster_id == -1)
        if cluster_id != -1:
            cluster_df = weekly_df[weekly_df['cluster_id'] == cluster_id]

            number_of_articles = len(cluster_df)

            # Ensure there are articles in the cluster before calculating mean embedding
            if number_of_articles > 0:
                # Convert list of embeddings to a NumPy array for mean calculation
                embeddings_array = np.array(cluster_df['bert_embeddings'].tolist())
                mean_embedding = embeddings_array.mean(axis=0)

                cluster_stats_list.append({
                    "week": week,
                    "cluster_id": cluster_id,
                    "count": number_of_articles,
                    "centroid": mean_embedding.tolist() # Store as list for DataFrame compatibility
                })

# Convert the list of dictionaries to a DataFrame for easier analysis
cluster_stats_df = pd.DataFrame(cluster_stats_list)

print("Cluster statistics calculated and stored in 'cluster_stats_df'.")
display(cluster_stats_df.head())

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

cluster_trends_data = []

for cluster_id in sorted(filtered_df['cluster_id'].unique()):
    if cluster_id == -1: # Skip noise points
        continue

    cluster_data = cluster_stats_df[cluster_stats_df['cluster_id'] == cluster_id].sort_values(by='week')

    # Use .apply() to convert each Period object in the Series to a Timestamp
    cluster_data['week_timestamp'] = cluster_data['week'].apply(lambda x: x.to_timestamp())

    if len(cluster_data) < 2:
        continue

    first_week_timestamp = cluster_data['week_timestamp'].iloc[0]

    prev_count = None
    prev_centroid = None
    prev_growth = None

    for index, row in cluster_data.iterrows():
        current_week = row['week']
        current_week_timestamp = row['week_timestamp']
        current_count = row['count']
        current_centroid = np.array(row['centroid']).reshape(1, -1)

        age_days = (current_week_timestamp - first_week_timestamp).days

        growth = 0.0
        drift = 0.0
        acceleration = 0.0

        if prev_count is not None:
            # Calculate growth
            if prev_count != 0:
                growth = (current_count - prev_count) / prev_count
            else:
                growth = np.inf # Handle division by zero

            # Calculate drift
            drift = 1 - cosine_similarity(current_centroid, prev_centroid)[0][0]

            # Calculate acceleration
            if prev_growth is not None:
                acceleration = growth - prev_growth

            cluster_trends_data.append({
                "week": current_week,
                "cluster_id": cluster_id,
                "age_days": age_days,
                "growth": growth,
                "drift": drift,
                "acceleration": acceleration
            })

        prev_count = current_count
        prev_centroid = current_centroid
        prev_growth = growth

cluster_trends_df = pd.DataFrame(cluster_trends_data)

print("Cluster trends calculated successfully.")
display(cluster_trends_df.head())

def classify_stage(age_days, growth, acceleration, drift):

    if growth < -0.2:
        return "declining" # decay detection

    if age_days <= 30:
        if growth > 0.3 or drift > 0.2:
            return "emerging"

    elif 30 < age_days <= 90:
        if growth > 0.1:
            return "trending"

    elif age_days >= 180:
        if acceleration < 0.05:
            return "established"

    return "stable" # 90-180 days cluster classifier

cluster_trends_df['stage'] = cluster_trends_df.apply(lambda row: classify_stage(
    row['age_days'],
    row['growth'],
    row['acceleration'],
    row['drift']
), axis=1)

print("Cluster stages classified successfully.")
display(cluster_trends_df.head())

cluster_trends_df['risk_score'] = (
    0.4 * cluster_trends_df['growth'] +
    0.3 * cluster_trends_df['acceleration'] +
    0.3 * cluster_trends_df['drift']
)

print("Risk scores calculated and added to 'cluster_trends_df'.")
display(cluster_trends_df.head())

print(cluster_trends_df)

print("Distribution of cluster stages:")
print(cluster_trends_df['stage'].value_counts())

print("Descriptive statistics for 'risk_score':")
display(cluster_trends_df['risk_score'].describe())

article_analysis = pd.merge(
    filtered_df,
    cluster_trends_df[['week', 'cluster_id', 'age_days', 'growth', 'drift', 'acceleration', 'stage', 'risk_score']],
    on=['week', 'cluster_id'],
    how='left'
)

print("Filtered DataFrame combined with cluster trends successfully.")
display(article_analysis.head())

# Displaying null counts to demonstrate where NaNs occur
print("\nNumber of NaN values per trend-related column in article_analysis:")
display(article_analysis[['age_days', 'growth', 'drift', 'acceleration', 'stage', 'risk_score']].isnull().sum())

print(f"Original df shape: {filtered_df.shape[0]} doc_ids")
print(f"Shape after dropping NaT from publish_timestamp: {article_analysis.shape[0]} doc_ids")

import numpy as np

# Select only the columns to upsert
columns_to_upsert = [
    'doc_id',
    'age_days',
    'growth',
    'drift',
    'acceleration',
    'stage',
    'risk_score'
]

# Create a DataFrame with only the relevant columns
df_to_upsert = article_analysis[columns_to_upsert].copy()

# Ensure 'stage' column is a string for Supabase
df_to_upsert['stage'] = df_to_upsert['stage'].astype(str)

# Fill any potential NaN values in numeric columns if necessary
# For simplicity, filling with 0 or a sensible default. Adjust if specific handling is needed.
df_to_upsert['age_days'] = df_to_upsert['age_days'].fillna(0).astype(int)
df_to_upsert['growth'] = df_to_upsert['growth'].fillna(0.0)
df_to_upsert['drift'] = df_to_upsert['drift'].fillna(0.0)
df_to_upsert['acceleration'] = df_to_upsert['acceleration'].fillna(0.0)
df_to_upsert['risk_score'] = df_to_upsert['risk_score'].fillna(0.0)


# Convert the DataFrame to a list of dictionaries
data_to_upsert = df_to_upsert.to_dict(orient='records')

CHUNK_SIZE = 50
print(f"Upserting {len(data_to_upsert)} records to Supabase table 'article_analysis'...")

for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        response = supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id" # Specify doc_id as the conflict key
        ).execute()
        # print(f"Successfully upserted chunk {i//CHUNK_SIZE + 1}. Response: {response.data}")
        print(f"Successfully upserted chunk {i//CHUNK_SIZE + 1} ({min(i + CHUNK_SIZE, len(data_to_upsert))} rows total)")
    except Exception as e:
        print(f"Failed to upsert chunk starting at index {i}: {e}")
        # Optionally, print the problematic chunk for debugging
        # print(f"Problematic chunk: {chunk}")

print("Upsert operation complete for article_analysis metrics.")

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Initialize the 'nearest_article' column to False
article_analysis['nearest_article'] = False

# Iterate through each unique cluster_id (excluding noise cluster -1)
for cluster_id in article_analysis['cluster_id'].unique():
    if cluster_id == -1:
        continue

    # Get articles belonging to the current cluster
    cluster_articles = article_analysis[article_analysis['cluster_id'] == cluster_id].copy()

    # Get the centroid for the current cluster and reshape it for cosine_similarity
    # Ensure we use the latest week's centroid or a representative one
    cluster_centroid_df = cluster_stats_df[
        (cluster_stats_df['cluster_id'] == cluster_id)
    ].sort_values(by='week', ascending=False).iloc[0]

    cluster_centroid = np.array(cluster_centroid_df['centroid']).reshape(1, -1)

    # Convert the list of embeddings for the cluster's articles into a NumPy array
    article_embeddings_in_cluster = np.array(cluster_articles['bert_embeddings'].tolist())

    # Calculate cosine similarity between each article and the cluster centroid
    similarities = cosine_similarity(article_embeddings_in_cluster, cluster_centroid)

    # Find the index of the article with the maximum similarity within this cluster
    closest_article_relative_index = np.argmax(similarities)

    # Get the doc_id of the closest article
    closest_article_doc_id = cluster_articles.iloc[closest_article_relative_index]['doc_id']

    # Update the 'nearest_article' column for the closest article in the original DataFrame
    article_analysis.loc[article_analysis['doc_id'] == closest_article_doc_id, 'nearest_article'] = True

print("Identified closest article to centroid for each cluster.")

# Display a sample of the updated DataFrame
display(article_analysis[article_analysis['nearest_article'] == True].head())


# Prepare data for upserting to Supabase
# Select only the doc_id and the new boolean column
df_closest_to_centroid = article_analysis[['doc_id', 'nearest_article']].copy()

# Convert to list of dictionaries
data_to_upsert_closest = df_closest_to_centroid.to_dict(orient='records')

CHUNK_SIZE = 50
print(f"Upserting {len(data_to_upsert_closest)} records to Supabase table 'article_analysis'...")

for i in range(0, len(data_to_upsert_closest), CHUNK_SIZE):
    chunk = data_to_upsert_closest[i : i + CHUNK_SIZE]
    try:
        response = supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id" # Specify doc_id as the conflict key
        ).execute()
        print(f"Successfully upserted chunk {i//CHUNK_SIZE + 1} ({min(i + CHUNK_SIZE, len(data_to_upsert_closest))} rows total)")
    except Exception as e:
        print(f"Failed to upsert chunk starting at index {i}: {e}")

print("Upsert operation complete for 'nearest_article' column.")